import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Nav from "./components/Navbar";
import { CookiesProvider } from "next-client-cookies/server";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  async function getCategories () {
    const res = await fetch('http://localhost:8080/api/categories', { cache: 'force-cache' })
    if (!res.ok) {
      throw new Error('Failed to fetch data')
    }
    return res.json()
  }
  const categories = await getCategories()

  return (
    <html lang="en" className='dark bg-blue-800'>
      <body>
        <CookiesProvider>
          <Providers>
            <Nav categories={categories} />
            <main className="flex max-h-screen flex-col items-center justify-between p-24">
              {children}
            </main>
          </Providers>
        </CookiesProvider>
      </body>
    </html>
  );
}
